# Code generated by TRAC

from __future__ import annotations
import typing as _tp  # noqa
import dataclasses as _dc  # noqa
import enum as _enum  # noqa

from .object_id import *  # noqa



@_dc.dataclass
class FileDefinition:

    name: str = None

    extension: str = None

    mimeType: str = None

    size: int = None

    storageId: TagSelector = None

    dataItem: str = None
