# coding: utf-8
"""
    Test Automation (No submodules)

    SDKs (no submodules) to test automation workflows.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from automation_test_no_submodules.client_custom import ClientCustom
from automation_test_no_submodules.configuration import Configuration
from automation_test_no_submodules.api_client import ApiClient
from automation_test_no_submodules.type_util import copy_signature
from automation_test_no_submodules.apis.tags.greetings_api import GreetingsApi



class AutomationTestNoSubmodules(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.greetings: GreetingsApi = GreetingsApi(api_client)
