# coding: utf-8

"""
    Spacestudio Orbit Propagation API

    <b>CHANGELOG</b> <ul>   <li><b>1.4.0</b> - 2024-07-05 - Add <b>initialDate</b> field in <b>OrbitPropagationRequest</b> schema</li>   <li><b>1.3.0</b> - 2024-07-03 - Add <b>atmosphericModel</b> and NRLMSISE00-related fields in <b>DragPerturbation</b> schema</li>   <li><b>1.2.0</b> - 2024-06-13 - Add <b>missionDuration</b> field in response payload</li>   <li><b>1.1.5</b> - 2024-06-06 - Improve API documentation</li>   <li><b>1.1.4</b> - 2024-05-28 - Improve API documentation</li>   <li><b>1.1.3</b> - 2024-05-28 - Improve API documentation</li>   <li><b>1.1.2</b> - 2024-05-28 - Improve API documentation</li>   <li><b>1.1.1</b> - 2024-05-28 - Delete <i>NONE</i> solar array type</li>   <li><b>1.1.0</b> - 2024-05-28 - Add perturbations and refactor API</li>   <li><b>1.0.0</b> - 2024-05-27 - Initial version</li> </ul> 

    The version of the OpenAPI document: 1.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "spacestudio-orbit-propagation"
VERSION = "1.4.1"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Spacestudio Orbit Propagation API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Spacestudio Orbit Propagation API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Exotrail",
    long_description_content_type='text/markdown',
    long_description="""\
    &lt;b&gt;CHANGELOG&lt;/b&gt; &lt;ul&gt;   &lt;li&gt;&lt;b&gt;1.4.0&lt;/b&gt; - 2024-07-05 - Add &lt;b&gt;initialDate&lt;/b&gt; field in &lt;b&gt;OrbitPropagationRequest&lt;/b&gt; schema&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.3.0&lt;/b&gt; - 2024-07-03 - Add &lt;b&gt;atmosphericModel&lt;/b&gt; and NRLMSISE00-related fields in &lt;b&gt;DragPerturbation&lt;/b&gt; schema&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.2.0&lt;/b&gt; - 2024-06-13 - Add &lt;b&gt;missionDuration&lt;/b&gt; field in response payload&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.1.5&lt;/b&gt; - 2024-06-06 - Improve API documentation&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.1.4&lt;/b&gt; - 2024-05-28 - Improve API documentation&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.1.3&lt;/b&gt; - 2024-05-28 - Improve API documentation&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.1.2&lt;/b&gt; - 2024-05-28 - Improve API documentation&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.1.1&lt;/b&gt; - 2024-05-28 - Delete &lt;i&gt;NONE&lt;/i&gt; solar array type&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.1.0&lt;/b&gt; - 2024-05-28 - Add perturbations and refactor API&lt;/li&gt;   &lt;li&gt;&lt;b&gt;1.0.0&lt;/b&gt; - 2024-05-27 - Initial version&lt;/li&gt; &lt;/ul&gt; 
    """,  # noqa: E501
    package_data={"spacestudio_orbit_propagation": ["py.typed"]},
)
