# SPDX-FileCopyrightText: 2022-2023 Helmholtz-Zentrum hereon GmbH
#
# SPDX-License-Identifier: EUPL-1.2

# Generated by Django 3.2.7 on 2022-03-01 17:39
# type: ignore

from django.db import migrations

import django_helmholtz_aai.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_helmholtz_aai", "0002_auto_20220214_1413"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="helmholtzuser",
            managers=[
                (
                    "objects",
                    django_helmholtz_aai.models.HelmholtzUserManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="helmholtzvirtualorganization",
            managers=[
                (
                    "objects",
                    django_helmholtz_aai.models.HelmholtzVirtualOrganizationManager(),
                ),
            ],
        ),
    ]
