# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/imu.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from synapse_pb import header_pb2 as synapse__pb_dot_header__pb2
from synapse_pb import vector3_pb2 as synapse__pb_dot_vector3__pb2
from synapse_pb import quaternion_pb2 as synapse__pb_dot_quaternion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synapse_pb/imu.proto',
  package='synapse_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14synapse_pb/imu.proto\x12\nsynapse_pb\x1a\x17synapse_pb/header.proto\x1a\x18synapse_pb/vector3.proto\x1a\x1bsynapse_pb/quaternion.proto\"\xa4\x02\n\x03Imu\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.synapse_pb.Header\x12+\n\x0borientation\x18\x02 \x01(\x0b\x32\x16.synapse_pb.Quaternion\x12\x1e\n\x16orientation_covariance\x18\x03 \x03(\x01\x12-\n\x10\x61ngular_velocity\x18\x04 \x01(\x0b\x32\x13.synapse_pb.Vector3\x12#\n\x1b\x61ngular_velocity_covariance\x18\x05 \x03(\x01\x12\x30\n\x13linear_acceleration\x18\x06 \x01(\x0b\x32\x13.synapse_pb.Vector3\x12&\n\x1elinear_acceleration_covariance\x18\x07 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[synapse__pb_dot_header__pb2.DESCRIPTOR,synapse__pb_dot_vector3__pb2.DESCRIPTOR,synapse__pb_dot_quaternion__pb2.DESCRIPTOR,])




_IMU = _descriptor.Descriptor(
  name='Imu',
  full_name='synapse_pb.Imu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='synapse_pb.Imu.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='synapse_pb.Imu.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation_covariance', full_name='synapse_pb.Imu.orientation_covariance', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='synapse_pb.Imu.angular_velocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_velocity_covariance', full_name='synapse_pb.Imu.angular_velocity_covariance', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='synapse_pb.Imu.linear_acceleration', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_acceleration_covariance', full_name='synapse_pb.Imu.linear_acceleration_covariance', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=409,
)

_IMU.fields_by_name['header'].message_type = synapse__pb_dot_header__pb2._HEADER
_IMU.fields_by_name['orientation'].message_type = synapse__pb_dot_quaternion__pb2._QUATERNION
_IMU.fields_by_name['angular_velocity'].message_type = synapse__pb_dot_vector3__pb2._VECTOR3
_IMU.fields_by_name['linear_acceleration'].message_type = synapse__pb_dot_vector3__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['Imu'] = _IMU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Imu = _reflection.GeneratedProtocolMessageType('Imu', (_message.Message,), {
  'DESCRIPTOR' : _IMU,
  '__module__' : 'synapse_pb.imu_pb2'
  # @@protoc_insertion_point(class_scope:synapse_pb.Imu)
  })
_sym_db.RegisterMessage(Imu)


# @@protoc_insertion_point(module_scope)
