# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/nav_sat_fix.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from synapse_pb import header_pb2 as synapse__pb_dot_header__pb2
from synapse_pb import nav_sat_status_pb2 as synapse__pb_dot_nav__sat__status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synapse_pb/nav_sat_fix.proto',
  package='synapse_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1csynapse_pb/nav_sat_fix.proto\x12\nsynapse_pb\x1a\x17synapse_pb/header.proto\x1a\x1fsynapse_pb/nav_sat_status.proto\"\xcf\x01\n\tNavSatFix\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.synapse_pb.Header\x12(\n\x06status\x18\x02 \x01(\x0b\x32\x18.synapse_pb.NavSatStatus\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x01\x12\x1b\n\x13position_covariance\x18\x06 \x03(\x01\x12 \n\x18position_covariance_type\x18\x07 \x01(\rb\x06proto3'
  ,
  dependencies=[synapse__pb_dot_header__pb2.DESCRIPTOR,synapse__pb_dot_nav__sat__status__pb2.DESCRIPTOR,])




_NAVSATFIX = _descriptor.Descriptor(
  name='NavSatFix',
  full_name='synapse_pb.NavSatFix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='synapse_pb.NavSatFix.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='synapse_pb.NavSatFix.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='synapse_pb.NavSatFix.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='synapse_pb.NavSatFix.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='synapse_pb.NavSatFix.altitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_covariance', full_name='synapse_pb.NavSatFix.position_covariance', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_covariance_type', full_name='synapse_pb.NavSatFix.position_covariance_type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=310,
)

_NAVSATFIX.fields_by_name['header'].message_type = synapse__pb_dot_header__pb2._HEADER
_NAVSATFIX.fields_by_name['status'].message_type = synapse__pb_dot_nav__sat__status__pb2._NAVSATSTATUS
DESCRIPTOR.message_types_by_name['NavSatFix'] = _NAVSATFIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NavSatFix = _reflection.GeneratedProtocolMessageType('NavSatFix', (_message.Message,), {
  'DESCRIPTOR' : _NAVSATFIX,
  '__module__' : 'synapse_pb.nav_sat_fix_pb2'
  # @@protoc_insertion_point(class_scope:synapse_pb.NavSatFix)
  })
_sym_db.RegisterMessage(NavSatFix)


# @@protoc_insertion_point(module_scope)
