# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/nav_sat_status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='synapse_pb/nav_sat_status.proto',
  package='synapse_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fsynapse_pb/nav_sat_status.proto\x12\nsynapse_pb\"/\n\x0cNavSatStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07service\x18\x02 \x01(\rb\x06proto3'
)




_NAVSATSTATUS = _descriptor.Descriptor(
  name='NavSatStatus',
  full_name='synapse_pb.NavSatStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='synapse_pb.NavSatStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='synapse_pb.NavSatStatus.service', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['NavSatStatus'] = _NAVSATSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NavSatStatus = _reflection.GeneratedProtocolMessageType('NavSatStatus', (_message.Message,), {
  'DESCRIPTOR' : _NAVSATSTATUS,
  '__module__' : 'synapse_pb.nav_sat_status_pb2'
  # @@protoc_insertion_point(class_scope:synapse_pb.NavSatStatus)
  })
_sym_db.RegisterMessage(NavSatStatus)


# @@protoc_insertion_point(module_scope)
