# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/pose.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from synapse_pb import point_pb2 as synapse__pb_dot_point__pb2
from synapse_pb import quaternion_pb2 as synapse__pb_dot_quaternion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synapse_pb/pose.proto',
  package='synapse_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15synapse_pb/pose.proto\x12\nsynapse_pb\x1a\x16synapse_pb/point.proto\x1a\x1bsynapse_pb/quaternion.proto\"X\n\x04Pose\x12#\n\x08position\x18\x01 \x01(\x0b\x32\x11.synapse_pb.Point\x12+\n\x0borientation\x18\x02 \x01(\x0b\x32\x16.synapse_pb.Quaternionb\x06proto3'
  ,
  dependencies=[synapse__pb_dot_point__pb2.DESCRIPTOR,synapse__pb_dot_quaternion__pb2.DESCRIPTOR,])




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='synapse_pb.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='synapse_pb.Pose.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='synapse_pb.Pose.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=178,
)

_POSE.fields_by_name['position'].message_type = synapse__pb_dot_point__pb2._POINT
_POSE.fields_by_name['orientation'].message_type = synapse__pb_dot_quaternion__pb2._QUATERNION
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'synapse_pb.pose_pb2'
  # @@protoc_insertion_point(class_scope:synapse_pb.Pose)
  })
_sym_db.RegisterMessage(Pose)


# @@protoc_insertion_point(module_scope)
