# Generated by Django 4.2.14 on 2024-07-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0002_alter_certificate_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        default="NL",
                        help_text="Two-letter country code",
                        max_length=2,
                        verbose_name="country name",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "The name of the organization, e.g. 'Gementee Amsterdam'"
                        ),
                        max_length=100,
                        verbose_name="organization name",
                    ),
                ),
                (
                    "state_or_province_name",
                    models.CharField(
                        blank=True,
                        help_text="The state or province name, e.g. 'Noord-Holland'",
                        max_length=100,
                        verbose_name="state or province name",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for the certificate",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        help_text="The common name for the certificate",
                        max_length=100,
                        verbose_name="common name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="certificate",
            name="info",
            field=models.OneToOneField(
                help_text="Information about the certificate",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="simple_certmanager.certificateinfo",
                verbose_name="certificate information",
            ),
        ),
    ]
