# Generated by Django 4.2.4 on 2023-08-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_auto_20200315_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='others_workitems_from',
            field=models.ManyToManyField(related_name='others_workitems_to', to='runtime.workitem'),
        ),
    ]
