# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_clock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import time_pb2 as time__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sim_clock.proto',
  package='synapse.msgs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsim_clock.proto\x12\x0csynapse.msgs\x1a\ntime.proto\x1a\x0cheader.proto\"\x97\x01\n\x08SimClock\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.synapse.msgs.Header\x12\"\n\x06system\x18\x02 \x01(\x0b\x32\x12.synapse.msgs.Time\x12 \n\x04real\x18\x03 \x01(\x0b\x32\x12.synapse.msgs.Time\x12\x1f\n\x03sim\x18\x04 \x01(\x0b\x32\x12.synapse.msgs.Timeb\x06proto3'
  ,
  dependencies=[time__pb2.DESCRIPTOR,header__pb2.DESCRIPTOR,])




_SIMCLOCK = _descriptor.Descriptor(
  name='SimClock',
  full_name='synapse.msgs.SimClock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='synapse.msgs.SimClock.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system', full_name='synapse.msgs.SimClock.system', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real', full_name='synapse.msgs.SimClock.real', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sim', full_name='synapse.msgs.SimClock.sim', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=211,
)

_SIMCLOCK.fields_by_name['header'].message_type = header__pb2._HEADER
_SIMCLOCK.fields_by_name['system'].message_type = time__pb2._TIME
_SIMCLOCK.fields_by_name['real'].message_type = time__pb2._TIME
_SIMCLOCK.fields_by_name['sim'].message_type = time__pb2._TIME
DESCRIPTOR.message_types_by_name['SimClock'] = _SIMCLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimClock = _reflection.GeneratedProtocolMessageType('SimClock', (_message.Message,), {
  'DESCRIPTOR' : _SIMCLOCK,
  '__module__' : 'sim_clock_pb2'
  # @@protoc_insertion_point(class_scope:synapse.msgs.SimClock)
  })
_sym_db.RegisterMessage(SimClock)


# @@protoc_insertion_point(module_scope)
