# coding: utf-8

# flake8: noqa

"""
    Aladdin Permission

    API contains operations on Aladdin Permission resource. Permissions cannot be applied directly to a user, they must be applied to a User Group first, then the user is added to a User Group. Note: This is not intended to be used for Authorization.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


__version__ = "1.0.0"

# import apis into sdk package
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.api.default_permission_api import DefaultPermissionAPI

# import ApiClient
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.api_response import ApiResponse
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.api_client import ApiClient
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.configuration import Configuration
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.exceptions import OpenApiException
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.exceptions import ApiTypeError
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.exceptions import ApiValueError
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.exceptions import ApiKeyError
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.exceptions import ApiAttributeError
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.exceptions import ApiException

# import models into sdk package
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.any import Any
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.permission_api_get_permission400_response import PermissionAPIGetPermission400Response
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.rpc_status import RpcStatus
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.v1_filter_permissions_request import V1FilterPermissionsRequest
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.v1_filter_permissions_response import V1FilterPermissionsResponse
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.v1_permission import V1Permission
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.v1_permission_query import V1PermissionQuery
from asdk_plugin_platform.agraph.platform.access.permission.v1.PermissionAPI.models.v1_permission_sensitivity_grade import V1PermissionSensitivityGrade
