
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-19T13:15:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aebe6ebf843b427f24a0d0330b17c3c5bc35e389",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
