
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-19T19:25:44+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6244509d564c35c04c44b1403ba8fff85e6ee1e8",
 "version": "0.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
