# generated by datamodel-codegen:
#   filename:  chamfer.json
#   timestamp: 2024-07-19T10:41:17+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, confloat

from . import placement


class IChamfer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Base: str = Field(..., description='The name of input object')
    Edge: confloat(ge=0.0) = Field(..., description='The edge index')
    Dist: confloat(ge=0.0) = Field(
        ..., description='The distance of the symmetric chamfer'
    )
    Placement: placement.Model
