# generated by datamodel-codegen:
#   filename:  fillet.json
#   timestamp: 2024-07-19T10:41:17+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat, confloat

from . import placement


class IFillet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Base: str = Field(..., description='The name of input object')
    Edge: confloat(ge=0.0) = Field(..., description='The edge index')
    Radius: PositiveFloat = Field(..., description='The radius for the fillet')
    Placement: placement.Model
