'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.25

version: 0.1.25

full_version: 0.1.25

git_revision: 0c134ed01e926bff7217f0a6a3b49ba599bf3865

release: True

'''
short_version: str = '0.1.25'
version: str = '0.1.25'
full_version: str = '0.1.25'
git_revision: str = '0c134ed01e926bff7217f0a6a3b49ba599bf3865'
release: bool = True
if not release:
    version = full_version
