# Generated by Django 2.2.11 on 2020-12-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('spam_auto', models.NullBooleanField(help_text='Automatic classification as spam/not spam')),
                ('spam', models.NullBooleanField(help_text='Classification as spam/not spam (possibly overridden manually)')),
                ('content', models.TextField()),
                ('confidence', models.SmallIntegerField(blank=True, help_text='Confidence of automated classification (0-100)', null=True)),
            ],
        ),
    ]
