__title__ = 'rtbold'
__description__ = 'Real Time Bold Motion Plotting'
__url__ = 'https://github.com/harvard-nrg/rtbold'
__version__ = '0.0.7'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
