from _typeshed import Incomplete
from amsdal_models.schemas.loaders.base import TransactionsLoaderBase as TransactionsLoaderBase
from collections.abc import Iterator
from pathlib import Path

class CliTransactionsLoader(TransactionsLoaderBase):
    _transactions_path: Incomplete
    def __init__(self, app_root: Path) -> None: ...
    def iter_transactions(self) -> Iterator[Path]: ...
    def __str__(self) -> str: ...

def _cleanup_transaction_file(source: str) -> str: ...
