from _typeshed import Incomplete
from oauthlib.oauth2.rfc6749.errors import ConsentRequired as ConsentRequired, InvalidRequestError as InvalidRequestError, LoginRequired as LoginRequired

log: Incomplete

class GrantTypeBase:
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value) -> None: ...
    async def validate_authorization_request(self, request): ...
    def id_token_hash(self, value, hashfunc=...): ...
    async def add_id_token(self, token, token_handler, request, nonce: Incomplete | None = None): ...
    def openid_authorization_validator(self, request): ...
OpenIDConnectBase = GrantTypeBase
