
NOT_FRESH_FLAG_ARGNAME = 'notfresh'
NOT_FRESH_FLAG_ARGNAME_ALIAS='old'
FRESH_FLAG_ARGNAME = 'fresh'
FRESH_FLAG_ARGNAME_ALIAS = 'new'
BALLIGATOR_FLAG_ARGNAME = 'balligator_flag'
BALLIGATOR_FLAG_ARGNAME_ALIAS = 'ba'

TALLIGATOR_FLAG_ARGNAME = 'talligator_flag'
TALLIGATOR_FLAG_ARGNAME_ALIAS = 'ta'
MFI_FLAG_ARGNAME = 'mfi_flag'
NO_MFI_FLAG_ARGNAME = 'no_mfi_flag'
MFI_FLAG_ARGNAME_ALIAS = 'mfi'
NO_MFI_FLAG_ARGNAME_ALIAS = 'nomfi'

#gator_oscillator_flag,go
GATOR_OSCILLATOR_FLAG_ARGNAME = 'gator_oscillator_flag'
GATOR_OSCILLATOR_FLAG_ARGNAME_ALIAS = 'go'

#keepbidask_flag,kba
KEEP_BID_ASK_FLAG_ARGNAME = 'keepbidask'
KEEP_BID_ASK_FLAG_ARGNAME_ALIAS = 'kba'
REMOVE_BID_ASK_FLAG_ARGNAME = 'rmbidask'
REMOVE_BID_ASK_FLAG_ARGNAME_ALIAS = 'rmba'

#quotescount
QUOTES_COUNT_ARGNAME = 'quotescount'
QUOTES_COUNT_ARGNAME_ALIAS = 'c'
#full flag
FULL_FLAG_ARGNAME = 'full'
FULL_FLAG_ARGNAME_ALIAS = 'uf'
NOT_FULL_FLAG_ARGNAME = 'notfull'
NOT_FULL_FLAG_ARGNAME_ALIAS = 'nf'

#dropna_volume
DROPNA_VOLUME_FLAG_ARGNAME = 'dropna_volume'
DROPNA_VOLUME_FLAG_ARGNAME_ALIAS = 'dv'
#dont_dropna_volume
DONT_DROPNA_VOLUME_FLAG_ARGNAME = 'dont_dropna_volume'
DONT_DROPNA_VOLUME_FLAG_ARGNAME_ALIAS = 'ddv'

_ARG_GROUP_POV_TITLE="POV"
_ARG_GROUP_POV_DESCRIPTION="Point of view"
_ARG_GROUP_RANGE_TITLE="DTRange"
_ARG_GROUP_RANGE_DESCRIPTION="Date and range selection"

_ARG_GROUP_INDICATOR_TITLE = 'Indicators'
_ARG_GROUP_INDICATOR_DESCRIPTION = 'Indicators flags'

_ARG_GROUP_BARS_TITLE="Bars"
_ARG_GROUP_BARS_DESCRIPTION="Bars flags"

_ARG_GROUP_CLEANUP_TITLE = 'Cleanup'
_ARG_GROUP_CLEANUP_DESCRIPTION = 'Cleanup data'

_ARG_GROUP_VERBOSITY_TITLE="Verbosity"
_ARG_GROUP_VERBOSITY_DESCRIPTION="control the verbosity of the output"

_ARG_GROUP_OUTPUT_TITLE="Output"
_ARG_GROUP_OUTPUT_DESCRIPTION="Output arguments"

_ARG_GROUP_INTERACTION_TITLE="Interaction"
_ARG_GROUP_INTERACTION_DESCRIPTION="Interaction arguments"
