# Generated by Django 5.0.6 on 2024-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_swupdate", "0004_firmwarerequest_retries_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmwarerequest",
            name="retry_interval",
        ),
        migrations.AddField(
            model_name="deploy",
            name="retries",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deploy",
            name="retry_interval",
            field=models.IntegerField(default=0),
        ),
    ]
