
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-17T15:50:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1da5f9f499132b3f9766e7b18c0ea874baf7abd0",
 "version": "0.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
