function(link_to_target targetName)
    if (NOT TARGET pthreads)
        if (MSVC)
            vcpkg_download(pthreads)
            find_package(pthreads CONFIG REQUIRED)
            add_library(pthreads ALIAS PThreads4W::PThreads4W)
        else()
            find_package(Threads)
            add_library(pthreads ALIAS Threads::Threads)
        endif()
    endif()
    target_link_libraries(${targetName} PRIVATE pthreads)
endfunction()