
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-16T08:02:15+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "8e755cee023615b7fe912896fcbccb7a3b19adda",
 "version": "0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
