# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/fhir/r4/proto/core/resources/medicinal_product_undesirable_effect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.fhir.core.proto import annotations_pb2 as google_dot_fhir_dot_core_dot_proto_dot_annotations__pb2
from google.fhir.r4.proto.core import datatypes_pb2 as google_dot_fhir_dot_r4_dot_proto_dot_core_dot_datatypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNgoogle/fhir/r4/proto/core/resources/medicinal_product_undesirable_effect.proto\x12\x13google.fhir.r4.core\x1a\x19google/protobuf/any.proto\x1a(google/fhir/core/proto/annotations.proto\x1a)google/fhir/r4/proto/core/datatypes.proto\"\xce\x06\n!MedicinalProductUndesirableEffect\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x17.google.fhir.r4.core.Id\x12\'\n\x04meta\x18\x02 \x01(\x0b\x32\x19.google.fhir.r4.core.Meta\x12\x30\n\x0eimplicit_rules\x18\x03 \x01(\x0b\x32\x18.google.fhir.r4.core.Uri\x12+\n\x08language\x18\x04 \x01(\x0b\x32\x19.google.fhir.r4.core.Code\x12,\n\x04text\x18\x05 \x01(\x0b\x32\x1e.google.fhir.r4.core.Narrative\x12\'\n\tcontained\x18\x06 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x31\n\textension\x18\x08 \x03(\x0b\x32\x1e.google.fhir.r4.core.Extension\x12:\n\x12modifier_extension\x18\t \x03(\x0b\x32\x1e.google.fhir.r4.core.Extension\x12W\n\x07subject\x18\n \x03(\x0b\x32\x1e.google.fhir.r4.core.ReferenceB&\xf2\xff\xfc\xc2\x06\x10MedicinalProduct\xf2\xff\xfc\xc2\x06\nMedication\x12\x46\n\x18symptom_condition_effect\x18\x0b \x01(\x0b\x32$.google.fhir.r4.core.CodeableConcept\x12<\n\x0e\x63lassification\x18\x0c \x01(\x0b\x32$.google.fhir.r4.core.CodeableConcept\x12\x45\n\x17\x66requency_of_occurrence\x18\r \x01(\x0b\x32$.google.fhir.r4.core.CodeableConcept\x12\x33\n\npopulation\x18\x0e \x03(\x0b\x32\x1f.google.fhir.r4.core.Population:U\xc0\x9f\xe3\xb6\x05\x03\xb2\xfe\xe4\x97\x06Ihttp://hl7.org/fhir/StructureDefinition/MedicinalProductUndesirableEffectJ\x04\x08\x07\x10\x08\x42\x8e\x01\n\x17\x63om.google.fhir.r4.coreP\x01Zkgithub.com/google/fhir/go/google/fhir/r4/proto/core/resources/medicinal_product_undesirable_effect_go_proto\x98\xc6\xb0\xb5\x07\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.fhir.r4.proto.core.resources.medicinal_product_undesirable_effect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.google.fhir.r4.coreP\001Zkgithub.com/google/fhir/go/google/fhir/r4/proto/core/resources/medicinal_product_undesirable_effect_go_proto\230\306\260\265\007\004'
  _MEDICINALPRODUCTUNDESIRABLEEFFECT.fields_by_name['subject']._options = None
  _MEDICINALPRODUCTUNDESIRABLEEFFECT.fields_by_name['subject']._serialized_options = b'\362\377\374\302\006\020MedicinalProduct\362\377\374\302\006\nMedication'
  _MEDICINALPRODUCTUNDESIRABLEEFFECT._options = None
  _MEDICINALPRODUCTUNDESIRABLEEFFECT._serialized_options = b'\300\237\343\266\005\003\262\376\344\227\006Ihttp://hl7.org/fhir/StructureDefinition/MedicinalProductUndesirableEffect'
  _MEDICINALPRODUCTUNDESIRABLEEFFECT._serialized_start=216
  _MEDICINALPRODUCTUNDESIRABLEEFFECT._serialized_end=1062
# @@protoc_insertion_point(module_scope)
