# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/fhir/r4/proto/core/resources/resource.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.fhir.core.proto import annotations_pb2 as google_dot_fhir_dot_core_dot_proto_dot_annotations__pb2
from google.fhir.r4.proto.core import datatypes_pb2 as google_dot_fhir_dot_r4_dot_proto_dot_core_dot_datatypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2google/fhir/r4/proto/core/resources/resource.proto\x12\x13google.fhir.r4.core\x1a(google/fhir/core/proto/annotations.proto\x1a)google/fhir/r4/proto/core/datatypes.proto\"\xc5\x04\n\x08Resource\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x17.google.fhir.r4.core.Id\x12\'\n\x04meta\x18\x02 \x01(\x0b\x32\x19.google.fhir.r4.core.Meta\x12\x30\n\x0eimplicit_rules\x18\x03 \x01(\x0b\x32\x18.google.fhir.r4.core.Uri\x12+\n\x08language\x18\x04 \x01(\x0b\x32\x19.google.fhir.r4.core.Code:\x8b\x03\xc0\x9f\xe3\xb6\x05\x03\xf0\xec\xc5\xe6\x06\x01\xb2\xfe\xe4\x97\x06\x30http://hl7.org/fhir/StructureDefinition/Resource\xb2\xf5\xf5\xd7\t\x19\n\x15\x46ilterSearchParameter\x10\t\xb2\xf5\xf5\xd7\t\x1b\n\x13ID-SEARCH-PARAMETER\x10\x04\x1a\x02id\xb2\xf5\xf5\xd7\t\x0c\n\x08_content\x10\x03\xb2\xf5\xf5\xd7\t\x14\n\x03_id\x10\x04\x1a\x0bResource.id\xb2\xf5\xf5\xd7\t+\n\x0c_lastUpdated\x10\x02\x1a\x19Resource.meta.lastUpdated\xb2\xf5\xf5\xd7\t#\n\x08_profile\x10\x08\x1a\x15Resource.meta.profile\xb2\xf5\xf5\xd7\t\n\n\x06_query\x10\x04\xb2\xf5\xf5\xd7\t%\n\t_security\x10\x04\x1a\x16Resource.meta.security\xb2\xf5\xf5\xd7\t!\n\x07_source\x10\x08\x1a\x14Resource.meta.source\xb2\xf5\xf5\xd7\t\x1b\n\x04_tag\x10\x04\x1a\x11Resource.meta.tagBr\n\x17\x63om.google.fhir.r4.coreP\x01ZOgithub.com/google/fhir/go/google/fhir/r4/proto/core/resources/resource_go_proto\x98\xc6\xb0\xb5\x07\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.fhir.r4.proto.core.resources.resource_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.google.fhir.r4.coreP\001ZOgithub.com/google/fhir/go/google/fhir/r4/proto/core/resources/resource_go_proto\230\306\260\265\007\004'
  _RESOURCE._options = None
  _RESOURCE._serialized_options = b'\300\237\343\266\005\003\360\354\305\346\006\001\262\376\344\227\0060http://hl7.org/fhir/StructureDefinition/Resource\262\365\365\327\t\031\n\025FilterSearchParameter\020\t\262\365\365\327\t\033\n\023ID-SEARCH-PARAMETER\020\004\032\002id\262\365\365\327\t\014\n\010_content\020\003\262\365\365\327\t\024\n\003_id\020\004\032\013Resource.id\262\365\365\327\t+\n\014_lastUpdated\020\002\032\031Resource.meta.lastUpdated\262\365\365\327\t#\n\010_profile\020\010\032\025Resource.meta.profile\262\365\365\327\t\n\n\006_query\020\004\262\365\365\327\t%\n\t_security\020\004\032\026Resource.meta.security\262\365\365\327\t!\n\007_source\020\010\032\024Resource.meta.source\262\365\365\327\t\033\n\004_tag\020\004\032\021Resource.meta.tag'
  _RESOURCE._serialized_start=161
  _RESOURCE._serialized_end=742
# @@protoc_insertion_point(module_scope)
