# Generated by Django 4.1.7 on 2023-04-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField()),
                ('is_check', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('adress', models.TextField(max_length=100)),
                ('is_status', models.BooleanField()),
                ('is_lock', models.BooleanField()),
                ('user_name', models.CharField(max_length=100)),
                ('avatar', models.BinaryField()),
            ],
        ),
    ]
