from .. import errors as errors
from .base import GrantTypeBase as GrantTypeBase
from _typeshed import Incomplete
from oauthlib import common as common

log: Incomplete

def code_challenge_method_s256(verifier, challenge): ...
def code_challenge_method_plain(verifier, challenge): ...

class AuthorizationCodeGrant(GrantTypeBase):
    default_response_mode: str
    response_types: Incomplete
    def create_authorization_code(self, request): ...
    async def create_authorization_response(self, request, token_handler): ...
    async def create_token_response(self, request, token_handler): ...
    async def validate_authorization_request(self, request): ...
    async def validate_token_request(self, request) -> None: ...
    def validate_code_challenge(self, challenge, challenge_method, verifier): ...
