# Generated by Django 5.0.6 on 2024-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "netbox_swupdate",
            "0002_monitoring_created_monitoring_custom_field_data_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deploy",
            name="state",
            field=models.CharField(default="STOPPED", max_length=10),
        ),
    ]
