# Generated by Django 5.0.6 on 2024-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "netbox_swupdate",
            "0005_remove_firmwarerequest_retry_interval_deploy_retries_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deploy",
            name="max_waiting_time",
            field=models.IntegerField(default=0),
        ),
    ]
