# Generated by Django 5.0.6 on 2024-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_swupdate", "0006_deploy_max_waiting_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploy",
            name="max_waiting_time",
            field=models.IntegerField(default=1),
        ),
    ]
