
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-18T17:14:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "527873a4a8ef497f0c1e5872df2ee7bff50bcc84",
 "version": "1.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
