
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-16T17:11:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2508db61a78553ca301faa1a57e4f73f347d3bd5",
 "version": "1.0.100"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
