# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt_zagrava/ccxt_zagrava/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt_zagrava.pro.htx import htx


class huobi(htx):

    def describe(self):
        return self.deep_extend(super(huobi, self).describe(), {
            'alias': True,
            'id': 'huobi',
        })
