# Generated by Django 3.1.7 on 2021-03-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='spam',
            field=models.BooleanField(help_text='Classification as spam/not spam (possibly overridden manually)', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='spam_auto',
            field=models.BooleanField(help_text='Automatic classification as spam/not spam', null=True),
        ),
    ]
