# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/fhir/core/proto/validation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'google/fhir/core/proto/validation.proto\x12\x1cgoogle.fhir.proto.validation\"\xe8\x02\n\x0eSqlRequirement\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x16\n\x0esql_expression\x18\x02 \x01(\t\x12\x42\n\x08severity\x18\x03 \x01(\x0e\x32\x30.google.fhir.proto.validation.ValidationSeverity\x12:\n\x04type\x18\x04 \x01(\x0e\x32,.google.fhir.proto.validation.ValidationType\x12\x14\n\x0c\x65lement_path\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x15\n\rfhir_path_key\x18\x07 \x01(\t\x12\x1c\n\x14\x66hir_path_expression\x18\x08 \x01(\t\x12\'\n\x1f\x66ields_referenced_by_expression\x18\t \x03(\t\x12 \n\x18\x66hir_path_sql_expression\x18\n \x01(\t*Z\n\x12ValidationSeverity\x12\x1a\n\x16SEVERITY_UNINITIALIZED\x10\x00\x12\x12\n\x0eSEVERITY_ERROR\x10\x01\x12\x14\n\x10SEVERITY_WARNING\x10\x02*\x8f\x02\n\x0eValidationType\x12!\n\x1dVALIDATION_TYPE_UNINITIALIZED\x10\x00\x12(\n$VALIDATION_TYPE_FHIR_PATH_CONSTRAINT\x10\x01\x12\x1f\n\x1bVALIDATION_TYPE_CARDINALITY\x10\x02\x12\x1f\n\x1bVALIDATION_TYPE_CHOICE_TYPE\x10\x05\x12#\n\x1fVALIDATION_TYPE_PRIMITIVE_REGEX\x10\x04\x12%\n!VALIDATION_TYPE_VALUE_SET_BINDING\x10\x06\x12\"\n\x1eVALIDATION_TYPE_REFERENCE_TYPE\x10\x07\x42$\n com.google.fhir.proto.validationP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.fhir.core.proto.validation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.google.fhir.proto.validationP\001'
  _VALIDATIONSEVERITY._serialized_start=436
  _VALIDATIONSEVERITY._serialized_end=526
  _VALIDATIONTYPE._serialized_start=529
  _VALIDATIONTYPE._serialized_end=800
  _SQLREQUIREMENT._serialized_start=74
  _SQLREQUIREMENT._serialized_end=434
# @@protoc_insertion_point(module_scope)
