# generated by datamodel-codegen:
#   filename:  cylinder.json
#   timestamp: 2024-07-19T10:41:17+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat

from . import placement


class ICylinder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Radius: PositiveFloat = Field(..., description='Radius of the cylinder')
    Height: PositiveFloat = Field(..., description='Height of the cylinder')
    Angle: PositiveFloat = Field(..., description='Angle of the cylinder')
    Placement: placement.Model
