# Autogenerated by devscripts/update-version.py

__version__ = '2024.07.16.232919'

RELEASE_GIT_HEAD = '37c233562db26dd3401fa188dbeb9cabdb284a62'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.07.16.232919dev'
