# Generated by Django 2.2.19 on 2021-03-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_auto_20210107_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='access_toket',
            field=models.CharField(default='', help_text='The ACCESS_TOKET given by MercadoPago.', max_length=100, verbose_name='access token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sandbox_token',
            field=models.CharField(default='', help_text='The SANDBOX_TOKET given by MercadoPago.', max_length=100, verbose_name='sandbox token'),
            preserve_default=False,
        ),
    ]
