# Generated by Django 2.2.19 on 2021-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_auto_20210321_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='received_content',
            field=models.TextField(default='', help_text='Conteúdo Recebido em JSON', verbose_name='Conteúdo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('o', 'Merchant Order'), ('p', 'Payment'), ('s', 'Subscription'), ('t', 'Test')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
