from typing import Any

def _merge_list_of_lists(parent: list[list[str]], child: list[list[str]]) -> list[list[str]]: ...
def _merge_list_fields(parent: list[Any], child: list[Any]) -> list[Any]: ...
def merge_schema(parent_schema: dict[str, Any], child_schema: dict[str, Any]) -> dict[str, Any]: ...
