# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='can.proto',
  package='synapse.msgs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcan.proto\x12\x0csynapse.msgs\x1a\x0cheader.proto\"w\n\x03\x43\x61n\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.synapse.msgs.Header\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0e\n\x06is_rtr\x18\x03 \x01(\x08\x12\x13\n\x0bis_extended\x18\x04 \x01(\x08\x12\x0b\n\x03\x64lc\x18\x05 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x06 \x03(\rb\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,])




_CAN = _descriptor.Descriptor(
  name='Can',
  full_name='synapse.msgs.Can',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='synapse.msgs.Can.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='synapse.msgs.Can.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_rtr', full_name='synapse.msgs.Can.is_rtr', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_extended', full_name='synapse.msgs.Can.is_extended', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dlc', full_name='synapse.msgs.Can.dlc', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='synapse.msgs.Can.data', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=160,
)

_CAN.fields_by_name['header'].message_type = header__pb2._HEADER
DESCRIPTOR.message_types_by_name['Can'] = _CAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Can = _reflection.GeneratedProtocolMessageType('Can', (_message.Message,), {
  'DESCRIPTOR' : _CAN,
  '__module__' : 'can_pb2'
  # @@protoc_insertion_point(class_scope:synapse.msgs.Can)
  })
_sym_db.RegisterMessage(Can)


# @@protoc_insertion_point(module_scope)
