# Generated by Django 3.2.6 on 2022-02-14 14:13

# Copyright (C) 2022 Helmholtz-Zentrum Hereon
# SPDX-FileCopyrightText: 2022-2023 Helmholtz-Zentrum hereon GmbH
#
# SPDX-License-Identifier: EUPL-1.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_helmholtz_aai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmholtzuser",
            name="eduperson_unique_id",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="helmholtzvirtualorganization",
            name="eduperson_entitlement",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
