# SPDX-FileCopyrightText: 2022-2023 Helmholtz-Zentrum hereon GmbH
#
# SPDX-License-Identifier: EUPL-1.2

# Generated by Django 3.2.25 on 2024-05-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_helmholtz_aai", "0003_auto_20220301_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="helmholtzuser",
            name="is_temporary",
            field=models.BooleanField(
                default=False,
                help_text="Has the user been created temporarily because the mapping is not yet finished?",
            ),
        ),
        migrations.AddField(
            model_name="helmholtzuser",
            name="userinfo",
            field=models.JSONField(
                help_text="Userinfo from the Helmholtz AAI.", null=True
            ),
        ),
    ]
