from . import utils as utils
from _typeshed import Incomplete
from oauthlib.common import extract_params as extract_params, urlencode as urlencode

def prepare_headers(oauth_params, headers: Incomplete | None = None, realm: Incomplete | None = None): ...
def prepare_form_encoded_body(oauth_params, body): ...
def prepare_request_uri_query(oauth_params, uri): ...
