from _typeshed import Incomplete

log: Incomplete

class RequestValidator:
    async def client_authentication_required(self, request, *args, **kwargs): ...
    async def authenticate_client(self, request, *args, **kwargs) -> None: ...
    async def authenticate_client_id(self, client_id, request, *args, **kwargs) -> None: ...
    async def confirm_redirect_uri(self, client_id, code, redirect_uri, client, request, *args, **kwargs) -> None: ...
    async def get_default_redirect_uri(self, client_id, request, *args, **kwargs) -> None: ...
    async def get_default_scopes(self, client_id, request, *args, **kwargs) -> None: ...
    async def get_original_scopes(self, refresh_token, request, *args, **kwargs) -> None: ...
    async def is_within_original_scope(self, request_scopes, refresh_token, request, *args, **kwargs): ...
    async def introspect_token(self, token, token_type_hint, request, *args, **kwargs) -> None: ...
    async def invalidate_authorization_code(self, client_id, code, request, *args, **kwargs) -> None: ...
    async def revoke_token(self, token, token_type_hint, request, *args, **kwargs) -> None: ...
    async def rotate_refresh_token(self, request): ...
    async def save_authorization_code(self, client_id, code, request, *args, **kwargs) -> None: ...
    async def save_token(self, token, request, *args, **kwargs): ...
    async def save_bearer_token(self, token, request, *args, **kwargs) -> None: ...
    async def validate_bearer_token(self, token, scopes, request) -> None: ...
    async def validate_client_id(self, client_id, request, *args, **kwargs) -> None: ...
    async def validate_code(self, client_id, code, client, request, *args, **kwargs) -> None: ...
    async def validate_grant_type(self, client_id, grant_type, client, request, *args, **kwargs) -> None: ...
    async def validate_redirect_uri(self, client_id, redirect_uri, request, *args, **kwargs) -> None: ...
    async def validate_refresh_token(self, refresh_token, client, request, *args, **kwargs) -> None: ...
    async def validate_response_type(self, client_id, response_type, client, request, *args, **kwargs) -> None: ...
    async def validate_scopes(self, client_id, scopes, client, request, *args, **kwargs) -> None: ...
    async def validate_user(self, username, password, client, request, *args, **kwargs) -> None: ...
    async def is_pkce_required(self, client_id, request): ...
    async def get_code_challenge(self, code, request) -> None: ...
    async def get_code_challenge_method(self, code, request) -> None: ...
    async def is_origin_allowed(self, client_id, origin, request, *args, **kwargs): ...
