# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synapse_pb/wheel_odometry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from synapse_pb import header_pb2 as synapse__pb_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synapse_pb/wheel_odometry.proto',
  package='synapse_pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fsynapse_pb/wheel_odometry.proto\x12\nsynapse_pb\x1a\x17synapse_pb/header.proto\"E\n\rWheelOdometry\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.synapse_pb.Header\x12\x10\n\x08rotation\x18\x02 \x01(\x01\x62\x06proto3'
  ,
  dependencies=[synapse__pb_dot_header__pb2.DESCRIPTOR,])




_WHEELODOMETRY = _descriptor.Descriptor(
  name='WheelOdometry',
  full_name='synapse_pb.WheelOdometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='synapse_pb.WheelOdometry.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='synapse_pb.WheelOdometry.rotation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=141,
)

_WHEELODOMETRY.fields_by_name['header'].message_type = synapse__pb_dot_header__pb2._HEADER
DESCRIPTOR.message_types_by_name['WheelOdometry'] = _WHEELODOMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WheelOdometry = _reflection.GeneratedProtocolMessageType('WheelOdometry', (_message.Message,), {
  'DESCRIPTOR' : _WHEELODOMETRY,
  '__module__' : 'synapse_pb.wheel_odometry_pb2'
  # @@protoc_insertion_point(class_scope:synapse_pb.WheelOdometry)
  })
_sym_db.RegisterMessage(WheelOdometry)


# @@protoc_insertion_point(module_scope)
