print("###                                     ######        ")
print(" #  #    # ##### ###### #      #      # #     # #   # ")
print(" #  ##   #   #   #      #      #      # #     #  # #  ")
print(" #  # #  #   #   #####  #      #      # ######    #   ")
print(" #  #  # #   #   #      #      #      # #         #   ")
print(" #  #   ##   #   #      #      #      # #         #   ")
print("### #    #   #   ###### ###### ###### # #         #   ")
print("\n")
print("A Python GUI for automatic Analyses of IntelliCage Data")
print("For more information see https://github.com/NiRuff/IntelliPy/")
print("\n")
print("Author: Nicolas Ruffini")
print("Please cite the related study if you use this software:")
print("Ruffini N, Müller MB, Schmitt U, Gerber S. IntelliPy: a GUI for analyzing IntelliCage data.")
print("Bioinformatics. 2021 Nov 5;37(21):3972-3973. doi: 10.1093/bioinformatics/btab682.")
print("PMID: 34601559; PMCID: PMC8570781.")