#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2404-37-g8f762bc3"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2404
#define NETGEN_VERSION_TWEAK 37
#define NETGEN_VERSION_HASH "g8f762bc3"
#endif // NETGEN_VERSION_HPP_INCLUDED
