"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.additive.v0.additive_simulation_pb2
import grpc
import typing

class SimulationServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Simulate: grpc.UnaryStreamMultiCallable[
        ansys.api.additive.v0.additive_simulation_pb2.SimulationRequest,
        ansys.api.additive.v0.additive_simulation_pb2.SimulationResponse] = ...

    UploadFile: grpc.StreamStreamMultiCallable[
        ansys.api.additive.v0.additive_simulation_pb2.UploadFileRequest,
        ansys.api.additive.v0.additive_simulation_pb2.UploadFileResponse] = ...

    DownloadFile: grpc.UnaryStreamMultiCallable[
        ansys.api.additive.v0.additive_simulation_pb2.DownloadFileRequest,
        ansys.api.additive.v0.additive_simulation_pb2.DownloadFileResponse] = ...

    Mesh: grpc.UnaryStreamMultiCallable[
        ansys.api.additive.v0.additive_simulation_pb2.MeshRequest,
        ansys.api.additive.v0.additive_simulation_pb2.MeshResponse] = ...


class SimulationServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Simulate(self,
        request: ansys.api.additive.v0.additive_simulation_pb2.SimulationRequest,
        context: grpc.ServicerContext,
    ) -> typing.Iterator[ansys.api.additive.v0.additive_simulation_pb2.SimulationResponse]: ...

    @abc.abstractmethod
    def UploadFile(self,
        request: typing.Iterator[ansys.api.additive.v0.additive_simulation_pb2.UploadFileRequest],
        context: grpc.ServicerContext,
    ) -> typing.Iterator[ansys.api.additive.v0.additive_simulation_pb2.UploadFileResponse]: ...

    @abc.abstractmethod
    def DownloadFile(self,
        request: ansys.api.additive.v0.additive_simulation_pb2.DownloadFileRequest,
        context: grpc.ServicerContext,
    ) -> typing.Iterator[ansys.api.additive.v0.additive_simulation_pb2.DownloadFileResponse]: ...

    @abc.abstractmethod
    def Mesh(self,
        request: ansys.api.additive.v0.additive_simulation_pb2.MeshRequest,
        context: grpc.ServicerContext,
    ) -> typing.Iterator[ansys.api.additive.v0.additive_simulation_pb2.MeshResponse]: ...


def add_SimulationServiceServicer_to_server(servicer: SimulationServiceServicer, server: grpc.Server) -> None: ...
