# Generated by Django 5.0.6 on 2024-07-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_swupdate", "0003_deploy_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmwarerequest",
            name="retries",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="firmwarerequest",
            name="retry_interval",
            field=models.IntegerField(default=0),
        ),
    ]
