from ccxt_zagrava.base.types import Entry


class ImplicitAPI:
    history_get_api_tw_history_pairname_resolution = historyGetApiTwHistoryPairNameResolution = Entry('api/tw/history/{pairName}/{resolution}', 'history', 'GET', {'cost': 1})
    public_get_trade_api_asset = publicGetTradeApiAsset = Entry('trade/api/asset', 'public', 'GET', {'cost': 1})
    public_get_trade_api_currencies = publicGetTradeApiCurrencies = Entry('trade/api/currencies', 'public', 'GET', {'cost': 1})
    public_get_trade_api_orderbooks_symbol = publicGetTradeApiOrderbooksSymbol = Entry('trade/api/orderbooks/{symbol}', 'public', 'GET', {'cost': 1})
    public_get_trade_api_orders = publicGetTradeApiOrders = Entry('trade/api/orders', 'public', 'GET', {'cost': 1})
    public_get_trade_api_pair_name = publicGetTradeApiPairName = Entry('trade/api/pair/{name}', 'public', 'GET', {'cost': 1})
    public_get_trade_api_pairs = publicGetTradeApiPairs = Entry('trade/api/pairs', 'public', 'GET', {'cost': 1})
    public_get_trade_api_pairs_precisions = publicGetTradeApiPairsPrecisions = Entry('trade/api/pairs/precisions', 'public', 'GET', {'cost': 1})
    public_get_trade_api_rates = publicGetTradeApiRates = Entry('trade/api/rates', 'public', 'GET', {'cost': 1})
    public_get_trade_api_trade_id = publicGetTradeApiTradeId = Entry('trade/api/trade/{id}', 'public', 'GET', {'cost': 1})
    public_get_trade_api_trades = publicGetTradeApiTrades = Entry('trade/api/trades', 'public', 'GET', {'cost': 1})
    public_get_trade_api_ccxt_zagrava_pairs = publicGetTradeApiccxt_zagravaPairs = Entry('trade/api/ccxt_zagrava/pairs', 'public', 'GET', {'cost': 1})
    public_get_trade_api_cmc_assets = publicGetTradeApiCmcAssets = Entry('trade/api/cmc/assets', 'public', 'GET', {'cost': 1})
    public_get_trade_api_cmc_orderbook_pair = publicGetTradeApiCmcOrderbookPair = Entry('trade/api/cmc/orderbook/{pair}', 'public', 'GET', {'cost': 1})
    public_get_trade_api_cmc_summary = publicGetTradeApiCmcSummary = Entry('trade/api/cmc/summary', 'public', 'GET', {'cost': 1})
    public_get_trade_api_cmc_ticker = publicGetTradeApiCmcTicker = Entry('trade/api/cmc/ticker', 'public', 'GET', {'cost': 1})
    public_get_trade_api_cmc_trades_pair = publicGetTradeApiCmcTradesPair = Entry('trade/api/cmc/trades/{pair}', 'public', 'GET', {'cost': 1})
    private_get_trade_api_ccxt_zagrava_balance = privateGetTradeApiccxt_zagravaBalance = Entry('trade/api/ccxt_zagrava/balance', 'private', 'GET', {'cost': 1})
    private_get_trade_api_ccxt_zagrava_order_id = privateGetTradeApiccxt_zagravaOrderId = Entry('trade/api/ccxt_zagrava/order/{id}', 'private', 'GET', {'cost': 1})
    private_get_trade_api_ccxt_zagrava_ordersofuser = privateGetTradeApiccxt_zagravaOrdersOfUser = Entry('trade/api/ccxt_zagrava/ordersOfUser', 'private', 'GET', {'cost': 1})
    private_get_trade_api_ccxt_zagrava_tradesofuser = privateGetTradeApiccxt_zagravaTradesOfUser = Entry('trade/api/ccxt_zagrava/tradesOfUser', 'private', 'GET', {'cost': 1})
    private_get_trade_api_transactionsofuser = privateGetTradeApiTransactionsOfUser = Entry('trade/api/transactionsOfUser', 'private', 'GET', {'cost': 1})
    private_post_trade_api_ccxt_zagrava_cancel_all_order = privatePostTradeApiccxt_zagravaCancelAllOrder = Entry('trade/api/ccxt_zagrava/cancel-all-order', 'private', 'POST', {'cost': 1})
    private_post_trade_api_ccxt_zagrava_cancelorder = privatePostTradeApiccxt_zagravaCancelorder = Entry('trade/api/ccxt_zagrava/cancelorder', 'private', 'POST', {'cost': 1})
    private_post_trade_api_ccxt_zagrava_ordercreate = privatePostTradeApiccxt_zagravaOrdercreate = Entry('trade/api/ccxt_zagrava/ordercreate', 'private', 'POST', {'cost': 1})
